feat(docs): add full examples for mongodb tasks
kestra-io/plugin-mongodb pull request #16
Opened 2024-08-26 03:49 UTC by shrutimantri

2024-08-27 13:41 UTC, wrussell1999 commented on src/main/java/io/kestra/plugin/mongodb/Load.java
> +                    from: "{{ inputs.file }}"
There is no input in this example

2024-08-27 14:43 UTC, shrutimantri commented on src/main/java/io/kestra/plugin/mongodb/InsertOne.java
> +                      _id:
This is correct. This is something specific to mongodb.

2024-08-28 00:50 UTC, wrussell1999 requested changes
Add inputs to a few examples and it’s good to go

2024-08-30 10:31 UTC, wrussell1999 approved these changes

2024-08-30 10:31 UTC, wrussell1999 commented on src/main/java/io/kestra/plugin/mongodb/Bulk.java
> +                  - id: file
```suggestion
                  - id: myfile
```

2024-08-30 10:31 UTC, wrussell1999 commented on src/main/java/io/kestra/plugin/mongodb/Bulk.java
> +                    from: "{{ inputs.file }}"
```suggestion
                    from: "{{ inputs.myfile }}"
```

2024-08-30 10:31 UTC, merged